// <auto-generated />
namespace LMSDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class All_LMS_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(All_LMS_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201810300417054_All_LMS_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
